### ISSUE TITLE
你好，感谢开源，建议在说明稳定上加上Vertx简单介绍

### ISSUE THREAD

**Issue by kkomge** [cloudoptlab/cloudopt-next#1]
很棒的项目，文档也比较清晰专业。但是刚开始我以为是底层依赖servlet容器，与作者沟通后发现原来是依赖于Vertx，为了避免更多人产生误解，建议在文档中增加Vertx简单介绍。

**Comment by T-baby** [comment]
等正式版出来后会有更详细的文档。感谢您的建议~
