### ISSUE TITLE
cloudopt-next-web包中有一个vertx的源文件但是没有用到

### ISSUE THREAD

**Issue by mealayaria** [cloudoptlab/cloudopt-next#13]
在io.vertx.ext.web.impl中，名为RoutingContextImpl，这个文件应该是vertx的源码吧，而且看起来也没有用到，是手滑还是有我不知道的作用呢？

**Comment by T-baby** [comment]
应该是vertx-web的源码，具体你可以看https://github.com/vert-x3/vertx-web

**Comment by mealayaria** [comment]
我知道是vertx-web的源码，但是我的意思是，如果用到vertx-web的话直接引入包就可以了，为何要自己再单独弄一份出来，而且这个文件在代码里没有别的地方用到，所以疑惑这个文件是不是手滑放进去的。

**Comment by mealayaria** [comment]
多谢解答！方便的话可以说明一下是什么bug吗？

**Comment by T-baby** [comment]
原本当404发生时会永远调用默认的404错误拦截器，所以自定义的错误拦截器就没法生效。

**Comment by mealayaria** [comment]
谢谢回复！
