### ISSUE TITLE
功能建议： 自动编译加载、Swagger、GraphQL、WebSocket

### ISSUE THREAD

**Issue by venliong** [cloudoptlab/cloudopt-next#14]
1. 在开发模式下支持热加载，`src`目录内容修改后自动编译、重新加载。可以参考`Ktor`和`ActFramework`
2. 通过注解、decorator生成swagger.json，SwaggerUI加载显示。`Spring Boot` `JFinal`支持此项功能
3. 集成`graphQL`和`graphiQL`
4. 增加WebSocket相关接口

**Comment by T-baby** [comment]
感谢建议，同时也欢迎您加入一起开发。

**Comment by T-baby** [comment]
目前已经支持自动编译加载、api文档自动生成、也增加了socket的相关支持。GraphQL 暂不考虑。

- [ ]
