### ISSUE TITLE
Feature Request: add support to convert form/query parameters to pojo object

### ISSUE THREAD

**Issue by edwardsayer** [cloudoptlab/cloudopt-next#15]
Feature Request: add support to convert form/querystring parameters to pojo object.
This may be implement with ObjectMapper from Jackson.

**Comment by T-baby** [comment]
Jooq itself is supported and can be used as a reference to jooq's documents.

**Comment by edwardsayer** [comment]
Ok, I didn't make myself clear.
What i mean is to provide url parameter injection like following code:
```kotlin
@GET("user")
fun get(User user){
        renderText(user.id + ":" + user.name)
}
```

**Comment by T-baby** [comment]
The next version considers support, and you are welcome to contribute code.
