### ISSUE TITLE
getBodyJson 方法不能转换为目标类型对象

### ISSUE THREAD

**Issue by tanqimin** [cloudoptlab/cloudopt-next#16]
`fun getBodyJson(clazz: Class<*>): Any? {
    return Jsoner.toJsonObject(Jsoner.toJsonString(context.bodyAsJson), clazz)
}`

初步怀疑：context.bodyAsJson获取的是JSONObject类型的对象，所以JSONObject结构并不能转换为clazz类型。

**Comment by tanqimin** [comment]
Buffer body = getBody();
JsonObject jsonObject = body.toJsonObject();
T t = jsonObject.mapTo(T.class);

这样是可以转成功的，所以，排除vertx的问题；

**Comment by T-baby** [comment]
在 #37805d923b7f81b44a35f70588a753d7431faa10 中尝试修复。
