### ISSUE TITLE
bug:如果application.json文件不存在，无法正常启动

### ISSUE THREAD

**Issue by cat9** [cloudoptlab/cloudopt-next#20]
类初始化问题，NextServer init先执行检测包名，包名空则抛异常了，导致NextServer.run(App.class)无法正常执行。
public static void main(String[] args) {
        NextServer.run(App.class);
    }

报错：
Caused by: java.lang.RuntimeException: Package name must not be null!
	at net.cloudopt.next.web.NextServer.scan(NextServer.kt:109)
	at net.cloudopt.next.web.NextServer.<clinit>(NextServer.kt:78)
	... 1 more

https://github.com/cloudoptlab/cloudopt-next/blob/65f04be0ec56c861279efaa27599ba6d671af009/cloudopt-next-web/src/main/kotlin/net/cloudopt/next/web/NextServer.kt#L78

**Comment by T-baby** [comment]
Hi，我们预计下个版本修复该问题，也欢迎提交 PR。

**Comment by T-baby** [comment]
已经在 https://github.com/cloudoptlab/cloudopt-next/commit/86bb2d389c26a6f4503c01d24d24a754902320f5 中修复。

**Comment by T-baby** [comment]
已经发版到 2.0.8.1-BETA
