### ISSUE TITLE
bug: logger的实现类造成崩溃

### ISSUE THREAD

**Issue by cat9** [cloudoptlab/cloudopt-next#21]
我的cookie是这样的：
Cookie       : "Phpstorm-385e8778=4b818d7f-e37d-49f1-bd6e-7a0ec9a27d09; PHPSESSID=luks4l55tj9j2t4c8actdkjnh3; Phpstorm-a03fb457=e86b135e-de94-4232-8e3f-b04158ee52fe; loggedon=26d1ebd4ec8c55cc69f190d0d37f6dac; filemanager=lg7p67m427lhmhe3tej9tefq00; fm_current_dir=D%3A%5C; _ga=GA1.1.701572348.1585020446; Phpstorm-66f14207=89186c57-4c50-4c74-ab23-4aa81b6bd591; io=VhmAg7_IBC33-941AAAA; JSESSIONID=B53DBEB5A049B01722CCC240BE257EC9"
其中%3A和%5C这种urlencode过的字符串，会被String.format误识别为标识符，造成格式化字符串报错。
Slf4JLogger 里面的实现，也有点问题，format之后又来一次*args。
logger.info("${Colorer.blue(Logger.configuration.infoPrefix)} ${String.format(message, *args)}", *args)

在实现上slf4j的logger比较好，使用的是{}来标识替代位置，这种不会造成格式化出错问题。

相关源码
https://github.com/cloudoptlab/cloudopt-next/blob/e14195406b7c24aa5797ab1470b1389b9217cb1d/cloudopt-next-web/src/main/kotlin/net/cloudopt/next/web/handler/ShowRouteHandler.kt#L51

https://github.com/cloudoptlab/cloudopt-next/blob/e14195406b7c24aa5797ab1470b1389b9217cb1d/cloudopt-next-logging/src/main/kotlin/net/cloudopt/next/logging/provider/Slf4jLoggerProvider.kt#L49

https://github.com/cloudoptlab/cloudopt-next/blob/e14195406b7c24aa5797ab1470b1389b9217cb1d/cloudopt-next-logging/src/main/kotlin/net/cloudopt/next/logging/provider/JdkLoggerProvider.kt#L70

**Comment by T-baby** [comment]
我们会尽快优化日志类的实现方式。

**Comment by T-baby** [comment]
已经修复。

**Comment by cat9** [comment]
另外，一般日志类的实现都是先判断是否显示，再执行格式化字符串以优化性能。优化的时候可以考虑一下。
预祝中秋国庆快乐~~

**Comment by T-baby** [comment]
有道理，可以考虑进去。

**Comment by T-baby** [comment]
已经发版到 2.0.8.1-BETA
