### ISSUE TITLE
部署到腾讯云 centos7 ，日志显示启动正常，但是任何请求都不响应。而在window 10上都正常。版本3.0.0.1.RELEASE

### ISSUE THREAD

**Issue by qianqian78** [cloudoptlab/cloudopt-next#37]
11:52:42,617 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
11:52:42,618 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
11:52:42,622 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [file:/work/powerdesign/classes/logback.xml]
11:52:42,623 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs multiple times on the classpath.
11:52:42,623 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [jar:file:/work/powerdesign/lib/cloudopt-next-web.jar!/logback.xml]
11:52:42,623 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [file:/work/powerdesign/classes/logback.xml]
11:52:42,748 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
11:52:42,749 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
11:52:42,756 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [STDOUT]
11:52:42,763 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
11:52:42,842 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to INFO
11:52:42,842 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[ROOT]
11:52:42,842 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
11:52:42,843 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@a74868d - Registering current configuration as safe fallback point

[Cloudopt Next] 2021-05-30 11:52:43 net.cloudopt.next.web.NextServer [INFO ] - ℹ️ INFO: ███╗   ██╗███████╗██╗  ██╗████████╗
[Cloudopt Next] 2021-05-30 11:52:43 net.cloudopt.next.web.NextServer [INFO ] - ℹ️ INFO: ████╗  ██║██╔════╝╚██╗██╔╝╚══██╔══╝
[Cloudopt Next] 2021-05-30 11:52:43 net.cloudopt.next.web.NextServer [INFO ] - ℹ️ INFO: ██╔██╗ ██║█████╗   ╚███╔╝    ██║
[Cloudopt Next] 2021-05-30 11:52:43 net.cloudopt.next.web.NextServer [INFO ] - ℹ️ INFO: ██║╚██╗██║██╔══╝   ██╔██╗    ██║
[Cloudopt Next] 2021-05-30 11:52:43 net.cloudopt.next.web.NextServer [INFO ] - ℹ️ INFO: ██║ ╚████║███████╗██╔╝ ██╗   ██║
[Cloudopt Next] 2021-05-30 11:52:43 net.cloudopt.next.web.NextServer [INFO ] - ℹ️ INFO: ╚═╝  ╚═══╝╚══════╝╚═╝  ╚═╝   ╚═╝
[Cloudopt Next] 2021-05-30 11:52:43 net.cloudopt.next.web.NextServer [INFO ] - ℹ️ INFO: Java Version: 11.0.9
[Cloudopt Next] 2021-05-30 11:52:43 net.cloudopt.next.web.NextServer [INFO ] - ℹ️ INFO: Java Provider: Red Hat, Inc.
[Cloudopt Next] 2021-05-30 11:52:43 net.cloudopt.next.web.NextServer [INFO ] - ℹ️ INFO: System: Linux
[Cloudopt Next] 2021-05-30 11:52:43 net.cloudopt.next.web.NextServer [INFO ] - ℹ️ INFO: Time: 2021-05-30 11:52:43
[Cloudopt Next] 2021-05-30 11:52:43 net.cloudopt.next.web.NextServer [INFO ] - ℹ️ INFO: Listener Port: 9090
[Cloudopt Next] 2021-05-30 11:52:43 net.cloudopt.next.web.NextServer [INFO ] - ℹ️ INFO: -------------------------------------------------------------------------------------------
[Cloudopt Next] 2021-05-30 11:52:43 com.zaxxer.hikari.HikariDataSource [INFO ] - HikariPool-1 - Starting...
[Cloudopt Next] 2021-05-30 11:52:44 com.zaxxer.hikari.HikariDataSource [INFO ] - HikariPool-1 - Start completed.
[Cloudopt Next] 2021-05-30 11:52:44 com.zaxxer.hikari.HikariDataSource [INFO ] - HikariPool-1 - Starting...
[Cloudopt Next] 2021-05-30 11:52:44 com.zaxxer.hikari.HikariDataSource [INFO ] - HikariPool-1 - Start completed.
[Cloudopt Next] 2021-05-30 11:52:44 net.cloudopt.next.web.NextServer [INFO ] - ℹ️ INFO: [PLUGIN] Registered plugin：net.cloudopt.next.jooq.JooqPlugin
[Cloudopt Next] 2021-05-30 11:52:44 net.cloudopt.next.web.NextServer [INFO ] - ℹ️ INFO: [FAILURE HANDLER] Registered failure handler：net.cloudopt.next.web.handler.DefaultErrorHandler
[Cloudopt Next] 2021-05-30 11:52:44 net.cloudopt.next.web.NextServer [INFO ] - ℹ️ INFO: [HANDLER] Registered handler：net.cloudopt.next.web.handler.CorsHandler
[Cloudopt Next] 2021-05-30 11:52:44 net.cloudopt.next.web.NextServer [INFO ] - ℹ️ INFO: [HANDLER] Registered handler：net.cloudopt.next.web.handler.CookieCorsHandler
[Cloudopt Next] 2021-05-30 11:52:44 net.cloudopt.next.web.NextServer [INFO ] - ℹ️ INFO: [HANDLER] Registered handler：net.cloudopt.next.web.handler.WafHandler
[Cloudopt Next] 2021-05-30 11:52:44 net.cloudopt.next.web.NextServer [INFO ] - ℹ️ INFO: [HANDLER] Registered handler：net.cloudopt.next.web.handler.ShowRouteHandler
[Cloudopt Next] 2021-05-30 11:52:44 net.cloudopt.next.web.NextServer [INFO ] - ℹ️ INFO: [RESOURCE] Registered resource POST :addCellMeta | /api/addCellMeta
[Cloudopt Next] 2021-05-30 11:52:44 net.cloudopt.next.web.NextServer [INFO ] - ℹ️ INFO: [RESOURCE] Registered resource GET :listGraphFile | /api/listGraphFile
[Cloudopt Next] 2021-05-30 11:52:44 net.cloudopt.next.web.NextServer [INFO ] - ℹ️ INFO: [RESOURCE] Registered resource POST :modifyGraph | /api/modifyGraph
[Cloudopt Next] 2021-05-30 11:52:44 net.cloudopt.next.web.NextServer [INFO ] - ℹ️ INFO: [RESOURCE] Registered resource GET :queryCellSchemaMap | /api/queryCellSchemaMap
[Cloudopt Next] 2021-05-30 11:52:44 net.cloudopt.next.web.NextServer [INFO ] - ℹ️ INFO: [RESOURCE] Registered resource POST :queryGraph | /api/queryGraph
[Cloudopt Next] 2021-05-30 11:52:44 net.cloudopt.next.web.NextServer [INFO ] - ℹ️ INFO: [RESOURCE] Registered resource GET :querySideBarGroups | /api/querySideBarGroups
[Cloudopt Next] 2021-05-30 11:52:44 net.cloudopt.next.web.NextServer [INFO ] - ℹ️ INFO: [RESOURCE] Registered resource POST :save | /api/save
[Cloudopt Next] 2021-05-30 11:52:44 net.cloudopt.next.web.NextServer [INFO ] - ℹ️ INFO: ==========================================================================================================
[Cloudopt Next] 2021-05-30 11:52:44 net.cloudopt.next.web.NextServer [INFO ] - ℹ️ INFO:  Cloudopt Next started success!
[Cloudopt Next] 2021-05-30 11:52:44 net.cloudopt.next.web.NextServer [INFO ] - ℹ️ INFO: http://127.0.0.1:9090
[Cloudopt Next] 2021-05-30 11:52:44 net.cloudopt.next.web.NextServer [INFO ] - ℹ️ INFO: ==========================================================================================================

[root@VM-0-6-centos ~]# curl http://127.0.0.1:9090/static/index.html
**curl: (52) Empty reply from server**

**Comment by qianqian78** [comment]
补充说明一下，未用maven-assembly-plugin打成一个独立的包（这种方式能运行没问题的），而是把依赖包一个个的放到lib目录下。

**Comment by qianqian78** [comment]
终于发现原因了：vert.x 4.03依赖netty 4.1.60，而cloudopt-next 依赖了netty 4.1.65。
所以，当不用fat jar时，netty 多版本jar就会冲突。
我是跟踪vert.x代码才发现的, io.vertx.core.http.impl.Http1xServerConnection.handleMessage()

**Comment by T-baby** [comment]
Hi，Next 是在 #36 时修改了 Netty 的版本号。在  Netty 1.60 版本之前存在三个漏洞。所以在升级时直接选用了最新的小版本。建议如果不使用 fat jar 的话，建议自行排除掉 Next 的 Netty 相关的依赖。

**Comment by T-baby** [comment]
经过测试有可能引入 gRPC 后也可能存在类似的问题，如果引入 gRPC 之类的插件发现 http 无法正常访问的话，有可能是出现了 netty 版本冲突的问题，需要将 gRPC 所依赖的 netty 版本或者是 cloudopt-next-web 依赖的 netty-all 排除掉。

**Comment by T-baby** [comment]
猜测是：https://github.com/eclipse-vertx/vert.x/issues/3897

近期会开始推进兼容更新。

**Comment by T-baby** [comment]
已经兼容

https://github.com/cloudoptlab/cloudopt-next/pull/41
