### ISSUE TITLE
请增加application.json的处理方式

### ISSUE THREAD

**Issue by qianqian78** [cloudoptlab/cloudopt-next#38]
希望支持从jar包外加载application.json ，因为fatjar里面的这个配置文件修改起来不方便。
我的想法是：
思路一，首先从文件系统的当前路径或config目录下加载的application.json文件，如果加载不到，再从jar包里加载。
思路二，文件系统或config目录下的application.json，和jar包里的application.json，合并到一起，且外部的application.json优先。

**Comment by T-baby** [comment]
预计下个版本会增加相关的工具类方法，方便读取外部文件。

**Comment by T-baby** [comment]
https://github.com/cloudoptlab/cloudopt-next/pull/41
