### ISSUE TITLE
kafka实现类、Auth认证类可以支持suspend方法

### ISSUE THREAD

**Issue by mayangzz** [cloudoptlab/cloudopt-next#46]
kafkacomsumer、auth继承实现类不能够支持suspend方法，await关键字不好使用

**Comment by T-baby** [comment]
下版本支持。

**Comment by T-baby** [comment]
在开发分支已支持。

https://github.com/cloudoptlab/cloudopt-next/commit/ce82cae2ce3d0e23a8934882573656029fbeeff7

https://github.com/cloudoptlab/cloudopt-next/commit/510319181e80bb9afede9f10788edad1242e7cf7

**Comment by T-baby** [comment]
已 合并 #50
