### ISSUE TITLE
JooqPaginate 在 init 中访问数据库

### ISSUE THREAD

**Issue by vincentha766** [cloudoptlab/cloudopt-next#48]
JooqPaginate 在 init { } 中调用了 count() 计算总行数，这样可能不合理。建议将 count() 放到 find() 中调用。

**Comment by T-baby** [comment]
下版本支持。

**Comment by T-baby** [comment]
在开发分支：https://github.com/cloudoptlab/cloudopt-next/commit/487bc58f53e2b901780d8a1842dbb91c68c7c304

已实现。

**Comment by T-baby** [comment]
已合并在 #50
