### ISSUE TITLE
在一个方法上添加两个自定义annotation，这两个自定义annotation都用@Before修饰，而只有一个Before的invokeBy类中的方法被调用。

### ISSUE THREAD

**Issue by qianqian78** [cloudoptlab/cloudopt-next#49]
//第一个annotation 
@Retention(AnnotationRetention.RUNTIME)
@Target(AnnotationTarget.FUNCTION)
@MustBeDocumented

@Before(invokeBy = [RoleCheck::class])
annotation class PreRole(
    val value: String,
)
//第二个annotation
@Retention(AnnotationRetention.RUNTIME)
@Target(AnnotationTarget.FUNCTION)
@MustBeDocumented

@Before(invokeBy = [PermissionCheck::class])
annotation class PreAuthorize(
    val value: String,
)

//
@API("/api/log")
class LogController : Resource() {

    @GET("/list")
    @PreRole("admin")
    @PreAuthorize("log:list")
    suspend fun list() {
      //......
    }
}

跟踪代码发现：
问题在NextServer.kt  第169行，beforeRouteHandlersTable[resourceUrl]?.get(httpMethod)?.plus(annotation)

**Comment by T-baby** [comment]
你好，最开始的时候设计没考虑到可能会有多个 before 或 after 一起混用，预计下版本解决。

**Comment by T-baby** [comment]
已经在开发分支上修复：https://github.com/cloudoptlab/cloudopt-next/commit/f6b5231a9b3e403b5ee37a949137c030a6dc1cca

**Comment by T-baby** [comment]
3.0.2.0-SNAPSHOT 版本已经更新了这个提交。
