### ISSUE TITLE
#42 没有实现，捕获的异常都是java.lang.NullPointerException

### ISSUE THREAD

**Issue by qianqian78** [cloudoptlab/cloudopt-next#51]

**Comment by T-baby** [comment]
方便看下代码吗？

**Comment by qianqian78** [comment]
调试发现，异常会被这里捕获：NextServerVerticle.kt   476行  -> resource.fail(500)
=========================================================
class SecurityAppServiceImpl :  SecurityAppService {

  suspend fun grant(roleId: Int, secrityIds: List<Int>): Boolean {
    if (roleId == 1) throw BizException("禁止为超级管理员角色分配权限")
  ....}
}
class SecurityController : Resource() {
    private var securityService: SecurityAppService = SecurityAppServiceImpl()

    @POST("/grantsecurity")

    suspend fun grantSecurity() {
        val body = (getBodyJson() as JsonObject)
        val roleId = body.getInteger(ROLEID)
        val securityIds = body.getJsonArray(SECURITYID)
        if (roleId == null || securityIds == null) {
            renderBadArgument()
        } else {
 
            val securityIds = mutableListOf<Int>().apply { securityIds.forEach { add(it as Int) } }
            if (securityService.grant(roleId, securityIds)) {
                renderOkJson()
            } else {
                renderFailJson("授权失败")
            }
        }
    }

**Comment by T-baby** [comment]
方便把 renderFailJson 的代码截图下吗？目前这段代码中没有看到抛出异常的部分。

**Comment by qianqian78** [comment]
> 方便把 renderFailJson 的代码截图下吗？目前这段代码中没有看到抛出异常的部分。
这个就是抛出的异常：
if (roleId == 1) throw BizException("禁止为超级管理员角色分配权限")

**Comment by T-baby** [comment]
我已经确认了这个问题，发现的确在传递异常信息时有可能引发空异常的问题。已经在 https://github.com/cloudoptlab/cloudopt-next/pull/52 中合并到主分支，今天会上传到中央仓。

**Comment by T-baby** [comment]
已在 https://github.com/cloudoptlab/cloudopt-next/pull/52 ，请使用 3.0.3.0
