### ISSUE TITLE
目前遇到的日志、数据库等问题

### ISSUE THREAD

**Issue by hectorqin** [cloudoptlab/cloudopt-next#53]
1.日志大段空白

![image](https://user-images.githubusercontent.com/14220132/141254920-0c7afa5a-af50-413f-b169-10457de418c7.png)

2.不支持多数据库链接

3.建议新增 gradle 示例

**Comment by hectorqin** [comment]
另外，加群好几天都没通过

**Comment by T-baby** [comment]
你好，日志大段空白的话说明对彩色日志支持得不好，建议将设置中的 logColor 改为 false。

关于多数据库连接的问题、gradle 的示例我们会考虑看看。欢迎贡献代码。

**Comment by hectorqin** [comment]
终端环境是  Item2 + zsh 哦

**Comment by T-baby** [comment]
不同终端和系统目前不是完美的兼容，我们会考虑换一个加颜色的库的，尝试关闭看看。

**Comment by hectorqin** [comment]
关闭颜色之后，日志显示正常了

另外，感觉配置不是很灵活，没有从环境变量里面读取配置，最重要的是 这个`env`配置，最好是能从环境变量中加载，且优先级更高

![image](https://user-images.githubusercontent.com/14220132/141422061-3531825e-26ae-4c1e-bc9b-fabd9a890e43.png)

**Comment by T-baby** [comment]
比较推荐的做法是用：

```kotlin
ConfigManager.initExternalConfigMap("D:/application.json")
```

然后将路径什么的通过 k8s 的 ConfigMap 映射过去，或者通过 docker 挂载一个文件。

如果不使用 docker 的话，纯通过环境变量，也可以将不同的文件的地址通过环境变量放入。

**Comment by hectorqin** [comment]
我的意思是 带有env的配置是不同环境的特殊配置，判断当前环境优先从环境变量里面读取。这样就可以实现   `application.json` 是通用配置，项目里面可以打包其他环境配置，通过配置 `env` 这个环境变量，来加载不同环境下的特殊配置

**Comment by T-baby** [comment]
嗯嗯，可以考虑。不过这样其实不是很安全。暂时你可以自己在代码中检测环境并按照代码重新加载下 json 即可。

**Comment by hectorqin** [comment]
ok
