### ISSUE TITLE
getRootClassPath错误

### ISSUE THREAD

**Issue by Ccixyj** [cloudoptlab/cloudopt-next#6]
Yamler的getRootClassPath方法在打jar包后运行出现异常.
![qq 20180322163343](https://user-images.githubusercontent.com/6183506/37759528-d4196e3e-2dee-11e8-888d-e32468f01170.png).
另外如果是jar的话,似乎获取路径类似D:\*****\*.jar!\com**\包名

**Comment by T-baby** [comment]
已在 https://github.com/cloudoptlab/cloudopt-next/commit/4078c1f42b319f30f506be695bfae316a68dbaa6 中修复。您可以直接删除掉maven的缓存并更新即可。

**Comment by Ccixyj** [comment]
测试了,没有问题了
