### ISSUE TITLE
JooqPaginate 返回的 count 字段意义

### ISSUE THREAD

**Issue by vincentha766** [cloudoptlab/cloudopt-next#62]
https://github.com/cloudoptlab/cloudopt-next/blob/abb891d927985f3032e047bb44aa36484806dc0d/plugins/cloudopt-next-jooq/src/main/kotlin/net/cloudopt/next/jooq/JooqPaginate.kt#L64

这里将输入的 count 直接返回了，如果查询的是最后一页，返回的记录条数可能小于传入的 count。建议这个返回字段改成 list.size()，代表实际返回的记录条数。

**Comment by T-baby** [comment]
最开始是为了记录最大行数，考虑下版本调整。
