### ISSUE TITLE
netty版本不一致，GraalVM打包netty报错，不知道是不是版本冲突引起。

### ISSUE THREAD

**Issue by 891806797** [cloudoptlab/cloudopt-next#68]
提几个小小的但是自我感觉非常重要的更新建议哈：
1、netty版本需要更新一下，目前用的3.0.3.0-RELEASE版本，依赖列表可以看到4.1.65跟4.1.75两个版本，然后我看Cloudopt-next饮用的4.1.65，希望可以统一升级为4.1.75，我这边使用GraalVM打包netty报错，不知道是不是由于版本冲突导致的，因此无法打包成native可执行文件。
2、日志那个handle（ShowRouteHandler）的@AutoHandler这个注解希望可以移除掉，目前不太符合我们项目需求，需要自定义，如果自定义，每次请求都打印两部分日志，非常难受。（文档里面的示例可以展示给用户，让用户选择是否要用这个handle，也可以模仿这个handle自定义自己的日志handle）

目前就以上两个问题希望可以尽快解决一下，谢谢各位开源作者可以贡献出这么优质，易用轻量的kotlin的服务端框架！

**Comment by T-baby** [comment]
第一个问题我近期会看看能否集成到下个版本。
第二个问题的话，可以在配置文件中将其关闭的，将 showRoute 的值改为 fasle 即可。

**Comment by 891806797** [comment]
好的多谢啦

**Comment by T-baby** [comment]
根据验证目前，Next 无法很好兼容 Graal Native 方案，除非重头重构。
