### ISSUE TITLE
Handle建议

### ISSUE THREAD

**Issue by Ccixyj** [cloudoptlab/cloudopt-next#8]
Handle是否可以修改为类似springmvc的 `preHandle`,`postHandle`,`afterCompletion`,以便做性能统计,方法耗时之类的
另外相同路径的`Interceptor`有多个的话,似乎后面的会覆盖前面的

**Comment by T-baby** [comment]
同路径的Interceptor覆盖问题已在https://github.com/cloudoptlab/cloudopt-next/commit/d27205e465a1013f59063c8fe16fa8ff153c2ee0 修复

**Comment by T-baby** [comment]
新的handler已在https://github.com/cloudoptlab/cloudopt-next/commit/e23a1e483af5d246e42a20786ed9c1ccceba03cd 实现。

**Comment by Ccixyj** [comment]
ok
