### ISSUE TITLE
Bug report: Cannot access classes in vertx-web dependency in SNAPSHOT

### ISSUE THREAD

**Issue by kiyoupio** [cloudoptlab/cloudopt-next#82]
When I use the SNAPSHOT version, the compilation reports an error after calling `context`.
![sendpix3](https://user-images.githubusercontent.com/86579709/180680196-31fb051c-227e-4516-9af0-b27ef952339c.jpg)

**Comment by T-baby** [comment]
This will be fixed in the next version.
