### ISSUE TITLE
Resourcer.kt 函数cleanText 删除/n，是有问题的。导致配置项中/n被删掉了。

### ISSUE THREAD

**Issue by qianqian78** [cloudoptlab/cloudopt-next#85]
private fun cleanText(jsonString: String): String {
        return jsonString.replace("/n", "")
 }
如下json配置项：
  "newkey": {
    "upload": "/work/website/newkeyict/ict/"
  },

**Comment by T-baby** [comment]
我会尽快找到一个更好的清理办法，预计在 3.1.0.0 发布，当然也欢迎你贡献，可以基于 3.x 分支。
